#version: '3'
services:
  nginx:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./html:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    command: [ "nginx", "-g", "daemon off;" ]
